### ISSUE TITLE
Configure MQTT for HomeAssistant

### ISSUE THREAD

**Issue by Cliff-R-K** [Andrea-Fox/peopleCounter#5]
Ok, I got some more stupid questions. I have a Zigbee2MQTT USB-Stick in my server and also dockers running a Mosquitto MQTT server and another docker running Home Assistant. The Zigbee2MQTT-usb sends everything to the MQTT server and they show up in Home Assistant in Integrations -> MQTT.

In the Mosquitto log I see:

```
1605812716: New connection from 192.168.0.182 on port 1883.
1605812716: New client connected from 192.168.0.182 as PeopleCounterESP32Client-a164 (p2, c1, k15).
```

But how do I make the device show up in Home Assistant ? 
I tried Adding the :
```
sensor:
    - platform: mqtt
      name: "People counter"
      state_topic: "peopleCounter/serialdata/tx"
```

But I get no new devices with or without the sensor added to config.yaml
